#!/usr/bin/env python3
"""Generate docs/tools.md from @mcp.tool functions in server.py."""
from __future__ import annotations

import argparse
import ast
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
SERVER = ROOT / "memorycore" / "server.py"
OUTPUT = ROOT / "docs" / "tools.md"


@dataclass
class Param:
    name: str
    annotation: str
    default: str


@dataclass
class Tool:
    name: str
    summary: str
    doc: str
    params: list[Param]
    returns: str


def _is_mcp_tool(node: ast.FunctionDef) -> bool:
    for decorator in node.decorator_list:
        func = decorator.func if isinstance(decorator, ast.Call) else decorator
        if (
            isinstance(func, ast.Attribute)
            and func.attr == "tool"
            and isinstance(func.value, ast.Name)
            and func.value.id == "mcp"
        ):
            return True
    return False


def _expr(node: ast.AST | None) -> str:
    if node is None:
        return ""
    return ast.unparse(node).replace("typing.", "")


def _default(node: ast.AST | None) -> str:
    if node is None:
        return "**required**"
    if isinstance(node, ast.Constant):
        if node.value is None:
            return "`None`"
        return f"`{node.value!r}`"
    return f"`{ast.unparse(node)}`"


def _escape_table(value: str) -> str:
    return value.replace("|", "\\|").replace("\n", " ")


def _params(args: ast.arguments) -> list[Param]:
    positional = list(args.posonlyargs) + list(args.args)
    defaults: list[ast.AST | None] = [None] * (len(positional) - len(args.defaults)) + list(args.defaults)
    params = [
        Param(arg.arg, _expr(arg.annotation) or "Any", _default(default))
        for arg, default in zip(positional, defaults, strict=True)
    ]
    kw_defaults = list(args.kw_defaults)
    params.extend(
        Param(arg.arg, _expr(arg.annotation) or "Any", _default(default))
        for arg, default in zip(args.kwonlyargs, kw_defaults, strict=True)
    )
    return params


def load_tools(server_path: Path = SERVER) -> list[Tool]:
    module = ast.parse(server_path.read_text(encoding="utf-8"))
    tools: list[Tool] = []
    for node in module.body:
        if not isinstance(node, ast.FunctionDef) or not _is_mcp_tool(node):
            continue
        doc = ast.get_docstring(node) or ""
        summary = doc.strip().splitlines()[0] if doc.strip() else "No docstring."
        tools.append(Tool(
            name=node.name,
            summary=summary,
            doc=doc.strip(),
            params=_params(node.args),
            returns=_expr(node.returns) or "Any",
        ))
    return tools


def render(tools: list[Tool]) -> str:
    lines: list[str] = [
        "# MCP Tool Reference",
        "",
        "<!-- This file is generated by scripts/generate_tools_doc.py. Do not edit by hand. -->",
        "",
        f"All {len(tools)} tools exposed by `memorycore` via the MCP protocol.",
        "Tools are listed in registration order from `memorycore/server.py`.",
        "Errors are caught by `@_safe_tool` and returned as JSON objects.",
        "",
        "## Tools",
        "",
    ]
    for tool in tools:
        lines.extend([
            f"### `{tool.name}`",
            "",
            tool.summary,
            "",
            f"**Returns:** `{_escape_table(tool.returns)}`",
            "",
        ])
        if tool.params:
            lines.extend([
                "| Parameter | Type | Default |",
                "|---|---|---|",
            ])
            for param in tool.params:
                lines.append(
                    f"| `{param.name}` | `{_escape_table(param.annotation)}` | {param.default} |"
                )
            lines.append("")
        else:
            lines.append("No parameters.")
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if docs/tools.md is not up to date")
    args = parser.parse_args(argv)

    generated = render(load_tools())
    if args.check:
        current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if current != generated:
            print("docs/tools.md is out of date; run scripts/generate_tools_doc.py", file=sys.stderr)
            return 1
        return 0
    OUTPUT.write_text(generated, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
